# Generated by Django 4.1.6 on 2023-04-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('Qty', models.IntegerField(max_length=100)),
            ],
        ),
    ]
