# Generated by Django 4.1.6 on 2023-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='catagory',
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Qty',
            field=models.IntegerField(null=True),
        ),
    ]
