# Generated by Django 4.1.6 on 2023-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_cart_qty_alter_cart_price_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
