# Generated by Django 4.1.6 on 2023-04-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_cart_singleprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
