# Generated by Django 4.1.6 on 2023-04-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='singleprice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
